/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermeniRouteImport } from './routes/termeni'
import { Route as ConfidentialitateRouteImport } from './routes/confidentialitate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DemoRestaurantRouteImport } from './routes/demo.restaurant'
import { Route as DemoRealestateRouteImport } from './routes/demo.realestate'
import { Route as DemoFitnessRouteImport } from './routes/demo.fitness'
import { Route as DemoEducationRouteImport } from './routes/demo.education'
import { Route as DemoClinicRouteImport } from './routes/demo.clinic'
import { Route as DemoBeautyRouteImport } from './routes/demo.beauty'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const TermeniRoute = TermeniRouteImport.update({
  id: '/termeni',
  path: '/termeni',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialitateRoute = ConfidentialitateRouteImport.update({
  id: '/confidentialitate',
  path: '/confidentialitate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRestaurantRoute = DemoRestaurantRouteImport.update({
  id: '/demo/restaurant',
  path: '/demo/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRealestateRoute = DemoRealestateRouteImport.update({
  id: '/demo/realestate',
  path: '/demo/realestate',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFitnessRoute = DemoFitnessRouteImport.update({
  id: '/demo/fitness',
  path: '/demo/fitness',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoEducationRoute = DemoEducationRouteImport.update({
  id: '/demo/education',
  path: '/demo/education',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClinicRoute = DemoClinicRouteImport.update({
  id: '/demo/clinic',
  path: '/demo/clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBeautyRoute = DemoBeautyRouteImport.update({
  id: '/demo/beauty',
  path: '/demo/beauty',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/termeni': typeof TermeniRoute
  '/demo/beauty': typeof DemoBeautyRoute
  '/demo/clinic': typeof DemoClinicRoute
  '/demo/education': typeof DemoEducationRoute
  '/demo/fitness': typeof DemoFitnessRoute
  '/demo/realestate': typeof DemoRealestateRoute
  '/demo/restaurant': typeof DemoRestaurantRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/termeni': typeof TermeniRoute
  '/demo/beauty': typeof DemoBeautyRoute
  '/demo/clinic': typeof DemoClinicRoute
  '/demo/education': typeof DemoEducationRoute
  '/demo/fitness': typeof DemoFitnessRoute
  '/demo/realestate': typeof DemoRealestateRoute
  '/demo/restaurant': typeof DemoRestaurantRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/termeni': typeof TermeniRoute
  '/demo/beauty': typeof DemoBeautyRoute
  '/demo/clinic': typeof DemoClinicRoute
  '/demo/education': typeof DemoEducationRoute
  '/demo/fitness': typeof DemoFitnessRoute
  '/demo/realestate': typeof DemoRealestateRoute
  '/demo/restaurant': typeof DemoRestaurantRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confidentialitate'
    | '/termeni'
    | '/demo/beauty'
    | '/demo/clinic'
    | '/demo/education'
    | '/demo/fitness'
    | '/demo/realestate'
    | '/demo/restaurant'
    | '/email/unsubscribe'
    | '/api/public/contact'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confidentialitate'
    | '/termeni'
    | '/demo/beauty'
    | '/demo/clinic'
    | '/demo/education'
    | '/demo/fitness'
    | '/demo/realestate'
    | '/demo/restaurant'
    | '/email/unsubscribe'
    | '/api/public/contact'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/confidentialitate'
    | '/termeni'
    | '/demo/beauty'
    | '/demo/clinic'
    | '/demo/education'
    | '/demo/fitness'
    | '/demo/realestate'
    | '/demo/restaurant'
    | '/email/unsubscribe'
    | '/api/public/contact'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfidentialitateRoute: typeof ConfidentialitateRoute
  TermeniRoute: typeof TermeniRoute
  DemoBeautyRoute: typeof DemoBeautyRoute
  DemoClinicRoute: typeof DemoClinicRoute
  DemoEducationRoute: typeof DemoEducationRoute
  DemoFitnessRoute: typeof DemoFitnessRoute
  DemoRealestateRoute: typeof DemoRealestateRoute
  DemoRestaurantRoute: typeof DemoRestaurantRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termeni': {
      id: '/termeni'
      path: '/termeni'
      fullPath: '/termeni'
      preLoaderRoute: typeof TermeniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialitate': {
      id: '/confidentialitate'
      path: '/confidentialitate'
      fullPath: '/confidentialitate'
      preLoaderRoute: typeof ConfidentialitateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/restaurant': {
      id: '/demo/restaurant'
      path: '/demo/restaurant'
      fullPath: '/demo/restaurant'
      preLoaderRoute: typeof DemoRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/realestate': {
      id: '/demo/realestate'
      path: '/demo/realestate'
      fullPath: '/demo/realestate'
      preLoaderRoute: typeof DemoRealestateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/fitness': {
      id: '/demo/fitness'
      path: '/demo/fitness'
      fullPath: '/demo/fitness'
      preLoaderRoute: typeof DemoFitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/education': {
      id: '/demo/education'
      path: '/demo/education'
      fullPath: '/demo/education'
      preLoaderRoute: typeof DemoEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/clinic': {
      id: '/demo/clinic'
      path: '/demo/clinic'
      fullPath: '/demo/clinic'
      preLoaderRoute: typeof DemoClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/beauty': {
      id: '/demo/beauty'
      path: '/demo/beauty'
      fullPath: '/demo/beauty'
      preLoaderRoute: typeof DemoBeautyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfidentialitateRoute: ConfidentialitateRoute,
  TermeniRoute: TermeniRoute,
  DemoBeautyRoute: DemoBeautyRoute,
  DemoClinicRoute: DemoClinicRoute,
  DemoEducationRoute: DemoEducationRoute,
  DemoFitnessRoute: DemoFitnessRoute,
  DemoRealestateRoute: DemoRealestateRoute,
  DemoRestaurantRoute: DemoRestaurantRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
